### ISSUE TITLE
__init__() got multiple values for argument 'reuse'

### ISSUE THREAD

**Issue by joyjeni** [isikdogan/deep_learning_tutorials#1]
I use tf version 1.12.0. I get TypeError 
https://colab.research.google.com/drive/1FtJArwnTTQ1zNoLXzZ5Bh5y4TG-JryUM

**Comment by isikdogan** [comment]
It worked when I copied it from here: https://github.com/isikdogan/deep_learning_tutorials/blob/master/S1/S1b_live.py

**Comment by joyjeni** [comment]
its working now
