### ISSUE TITLE
Cannot batch tensors with different shapes in component 0. 

### ISSUE THREAD

**Issue by joyjeni** [isikdogan/deep_learning_tutorials#2]
When I run trainer.py from session 6 I get below error.

InvalidArgumentError (see above for traceback): Cannot batch tensors with different shapes in component 0. First element had shape [220,195,3] and element 1 had shape [339,460,3].
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?,?,3], [?]], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](data/Iterator)]]

**Comment by isikdogan** [comment]
It seems that the images in your dataset have different sizes. You can try resizing them all to the same size before training. I wrote this helper script to do so: https://github.com/isikdogan/deep_learning_tutorials/blob/master/S6/resize_images.py

**Comment by joyjeni** [comment]
yes. it's working now. Thank you!
