### ISSUE TITLE
Exclude logit layer 

### ISSUE THREAD

**Issue by abdullah-alghamdi** [isikdogan/deep_learning_tutorials#3]
Hi Leo, 
Thanks for this tutorial! 

For some reason my network is not being fine-tuned well, not sure if the problem is in my data. However, I wonder if we have to exclude the logit layer when we restore the weights? 

Thanks again.

**Comment by isikdogan** [comment]
Hi, sure! I haven't thoroughly tested the code. What dataset are you using? We exclude the output layer because the number of classes is different in the dataset we are transferring the weights from.
